### PR TITLE
Fixed "redirect_uri does not match" error

### PR DESCRIPTION
**Pull request by tinbka**

### CODE REVIEW

**Comment by radar** [comment]
What does it generate without this patch and with this patch?

**Comment by tinbka** [comment]
In my case callback_url generated
`"https://b9d369e8.ngrok.io/auth/lightspeed/callback?code=b9ef470e1c42e4b1e2a7f292116f42324e55f1fe&state=fc7b5e818bcbd7790396c9a115d525be21875224104ae337"`
and since in Lightspeed OAuth console there is a path without query, it was producing error:
`#<OAuth2::Error: redirect_uri_mismatch: The redirect URI is missing or do not match
{"error":"redirect_uri_mismatch","error_description":"The redirect URI is missing or do not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-4.1.3"}>`

I've fixed this by dropping out _query_ part.

**Comment by radar** [comment]
This looks to be the same as #1.

You need the query parameters to exist in the URL, as the `code` is the OAuth token and `state` represents a nonce that's used for the entire OAuth process.

**Comment by radar** [comment]
However, since it's now been reported twice it's probably best to just merge it...

**Comment by tinbka** [comment]
That's basically true for _token_ phase, but it uses #callback_url for _authorize_ phase and not for _token_ one.

**Pull request merged**
