### PR TITLE
Remove query parameters from callback_url for token access

### PR DESCRIPTION
**Pull request by hayesgm**
When using this gem, I am getting a invalid request URI (does not match) during the access token phase. This is due to the callback_url containing query parameters (token and code). This patch removes those from the `callback_url` to match the expectation of Lightspeed's OAuth server.

### CODE REVIEW

**Comment by radar** [comment]
Doesn't the callback URL receive the token which is used for authenticating after that point? I don't think I want to remove all query parameters here. This code is working fine in production.

**Comment by radar** [comment]
See Section 4.2.2 here: https://tools.ietf.org/html/rfc6749#section-4.2.2.

**Comment by hayesgm** [comment]
Sure, I don't understand why this is being rejected by the remote server. I was able to mitigate the issue I'm facing by setting a token param to override `redirect_uri`, e.g.

```ruby
provider :lightspeed,
    client_id,
    client_secret,
    scope: 'employee:all',
    token_params: { redirect_uri: "http://localhost:3000/auth/lightspeed/callback" }
```

But I can assure you that when `callback_url == http://localhost:3000/auth/lightspeed/callback?code=xxx&state=yyy`, this line raises with an invalid `redirect_uri`:

client.auth_code.get_token(verifier, {:redirect_uri => callback_url}.merge(token_params.to_hash(:symbolize_keys => true)), deep_symbolize(options.auth_token_params))

and when I override `redirect_uri` with `http://localhost:3000/auth/lightspeed/callback` directly, that line passes back a valid token.

**Comment by radar** [comment]
Please reach out to lightspeed support regarding this. I cannot debug it from over here.

**Comment by hayesgm** [comment]
Sure, the workaround with `token_params` makes this pull request moot anyway. Thanks for your help.

**Pull request closed without merging**
